baseURL = "https://inetlab.yamanashi.ac.jp/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "InetLab@Yamanashi"
theme = "PaperMod"

enableRobotsTXT = true
canonifyURLs = false

[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false

[menu]
  [[menu.main]]
    name = "研究"
    url = "/research/"
    weight = 10
  [[menu.main]]
    name = "メンバー"
    url = "/members/"
    weight = 20
  [[menu.main]]
    name = "配属希望"
    url = "/prospective/"
    weight = 30
  [[menu.main]]
    name = "アクセス"
    url = "/access/"
    weight = 40
  [[menu.main]]
    name = "EN (auto)"
    url = "https://translate.google.com/translate?sl=ja&tl=en&u=https%3A%2F%2Finetlab-yamanashi.github.io%2F"
    weight = 50

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"