baseURL = "https://inetlab-yamanashi.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "InetLab@Yamanashi"
theme = "PaperMod"

enableRobotsTXT = true
canonifyURLs = false

[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    name = "研究"
    url = "/research/"
    weight = 10
  [[menu.main]]
    name = "メンバー"
    url = "/members/"
    weight = 20
  [[menu.main]]
    name = "連絡先"
    url = "/contact/"
    weight = 30
  [[menu.main]]
    name = "English (auto)"
    url = "https://translate.google.com/translate?sl=ja&tl=en&u=https%3A%2F%2Finetlab-yamanashi.github.io%2F"
    weight = 40